# Generated by Django 3.0.6 on 2020-05-07 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('main_image', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='blog')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
