# Generated by Django 3.0.6 on 2020-05-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
    ]
